name: checkbox_formfield
description: This package contains checkbox widgets that can be used as FormField for Flutter beginners.
version: 0.1.2
homepage: https://reidha.github.io/
repository: https://github.com/reidha/checkbox_formfield

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
