name: checkbox_formfield
description: This package contains checkbox widgets that can be used as FormField for Flutter beginners.
version: 1.0.0
homepage: https://reidha.github.io/
repository: https://github.com/reidha/checkbox_formfield

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
